<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6077" started-at="2018-02-14T18:42:50Z" finished-at="2018-02-14T18:42:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6077" started-at="2018-02-14T18:42:50Z" finished-at="2018-02-14T18:42:56Z">
      <class name="Exercises.Exercise9a">
        <test-method status="FAIL" signature="testExercise9a()[pri:0, instance:Exercises.Exercise9a@d8355a8]" name="testExercise9a" duration-ms="6061" started-at="2018-02-14T13:42:50Z" finished-at="2018-02-14T13:42:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<You logged into a secure area!> but was:<You logged into a secure area!
×>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<You logged into a secure area!> but was:<You logged into a secure area!
×>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at Exercises.Exercise9a.testExercise9a(Exercise9a.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testExercise9a -->
      </class> <!-- Exercises.Exercise9a -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
